### ISSUE TITLE
How to reset the routing cache 

### ISSUE THREAD

**Issue by ak274** [framasev/ng-cache-route-reuse#1]
Suppose after logout i want to clear the entire cache how would i do that with service?

**Comment by framasev** [comment]
@ak274 Extended the service with "clear" method. Update the library.

**Comment by ak274** [comment]
Thanks! For quick implementation. It was a straight forward change removing all the entries from Map. But what if I want to remove only one specific route after sometime. Can I do that out of the box?

**Comment by ak274** [comment]
@framasev Is there any solution to remove specific routes/component from the cached routes so that when i come back to that page it gets initiated again and not get attached from cached routes?

**Comment by framasev** [comment]
@ak274 Out of the box - no. But i can extend the service with "delete" operation to give more control over a store. It will be a simple change as the previous issue.

**Comment by ak274** [comment]
In service:---

```
public delete(component: string | Type<any>) {
    this.storeService.delete(component);
  }
```

And consumer can use:-- 

```
delete(component: string | Type<any>) {
    this.cacheService.delete(component);
  }
```

What do you think?

**Comment by framasev** [comment]
Will emit 'onAttach' event - that is not quite correct:
```typescript
/* Service */
public delete(component: string | Type<any>) {
  this.storeService.delete(component);
}
```

Will work, but "deleting" will be silent:
```typescript
/* Service */
public delete(component: string | Type<any>) {
  this.storeService.delete(component, false);
}
```
```typescript
/* Store */
public delete(component: string | Type<any>, emitEvent: boolean = true): boolean {
  const removed = super.delete(component);
  if (removed && emitEvent) { this.dispatch(StoreAction.Delete, component); }
  return removed;
}
```
