### ISSUE TITLE
Cannot reattach ActivatedRouteSnapshot created from a different route

### ISSUE THREAD

**Issue by ak274** [framasev/ng-cache-route-reuse#3]
It seems like when i'm trying to use this package for reuse strategy it fails in cases when child routes are there for same kind of route and need to update the strategy. It's a similar to below mentioned  issue. 

https://github.com/angular/angular/issues/13869

Suppose i went to :--

`http://localhost:4200/task/list ` it works fine first time. 
And then i want to go to a link suppose :-- `http://localhost:4200/task/details ` and from there if i want to go to a child link of list :-- `http://localhost:4200/task/list/edit/34 `
it throw error:--

```
core.js:4196 ERROR Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot created from a different route
Error: Cannot reattach ActivatedRouteSnapshot created from a different route

```

**Comment by framasev** [comment]
@ak274 Provide a minimal reproduction, please.
